name: Deploy React App
on: 
  push: 
    branches: 
      - main
jobs: 
  test-react:
    runs-on: ubuntu-latest
    steps: 
      - name: Get the rep code
        uses: actions/checkout@v3 
      - name: Cache deps
        uses: actions/cache@v3
        with: 
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/pacage-lock.json')}}
      - name: Install dep
        run: npm ci
      - name: Test app
        run: npm run test
  lint-react:
    runs-on: ubuntu-latest
    steps: 
      - name: Get the rep code
        uses: actions/checkout@v3 
      - name: Cache deps
        uses: actions/cache@v3
        with: 
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/pacage-lock.json')}}
      - name: Install dep
        run: npm ci
      - name: Test app
        run: npm run lint
  build-react:
    runs-on: ubuntu-latest
    needs: [lint-react,test-react]
    strategy:
      matrix:
        node-vers: [14, 16]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps: 
      - name: Get the rep code
        uses: actions/checkout@v3 
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with: 
          node-version: ${{matrix.node-vers}}
      - name: Cache deps
        uses: actions/cache@v3
        with: 
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/pacage-lock.json')}}
      - name: Install dep
        run: npm ci
      - name: Test app
        run: npm run build
      - name: Deploy  
        run: echo Deploying...