name: Deploy React App
on: 
  push: 
    branches: 
      - main
jobs: 
  test-react:
    runs-on: ubuntu-latest
    steps: 
      - name: Get the rep code
        uses: actions/checkout@v3 
      - name: Cache deps
        uses: actions/cache@v3
        with: 
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/pacage-lock.json')}}
      - name: Install dep
        run: npm ci
      - name: Test app
        run: npm run test
  lint-react:
    runs-on: ubuntu-latest
    needs: test-react
    steps: 
      - name: Get the rep code
        uses: actions/checkout@v3 
      - name: Cache deps
        uses: actions/cache@v3
        with: 
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/pacage-lock.json')}}
      - name: Install dep
        run: npm ci
      - name: Test app
        run: npm run lint
  build-react:
    runs-on: ubuntu-latest
    needs: lint-react
    steps: 
      - name: Get the rep code
        uses: actions/checkout@v3 
      - name: Cache deps
        uses: actions/cache@v3
        with: 
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/pacage-lock.json')}}
      - name: Install dep
        run: npm ci
      - name: Test app
        run: npm run build
      - name: Deploy  
        run: echo Deploying...