name: Test React App
on: push
jobs: 
  test-react:
    runs-on: ubuntu-latest
    steps: 
      - name: Get the rep code
        uses: actions/checkout@v3 
      - name: Install dep
        run: npm ci
      - name: Test app
        run: npm run test